1.Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [212]:
import pandas as pd
lst=[10, 20, 30, 40, 50]
create_series=pd.Series(lst,name='ID')
# print(create_series)
# create_series
print(create_series.to_frame())
print(type(create_series))
print(create_series.index)

   ID
0  10
1  20
2  30
3  40
4  50
<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=5, step=1)

In [213]:
#create dataframe
df={
    "Name":['Alice','Bob','Charli','Ajme'],
    "Age":[12,22,45,66],
    'City':['A','B','C','D']
}
df=pd.DataFrame(df)
df

     Name  Age City
0   Alice   12    A
1     Bob   22    B
2  Charli   45    C
3    Ajme   66    D

2.Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [214]:
print(type(df))
print(df['Name']) #column
print(df.loc[0:1])
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
0     Alice
1       Bob
2    Charli
3      Ajme
Name: Name, dtype: object
    Name  Age City
0  Alice   12    A
1    Bob   22    B
             Age
count   4.000000
mean   36.250000
std    24.171264
min    12.000000
25%    19.500000
50%    33.500000
75%    50.250000
max    66.000000

3.
Create a DataFrame using the dictionary below:


data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

Print .columns, .index. Access a single column and one full row.

In [215]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data=pd.DataFrame(data)
data

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [216]:
print(data[['Product','Price']])

  Product  Price
0     Pen     10
1    Book     50
2  Eraser      5
3  Pencil      7

In [217]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [218]:
print(data.loc[0:0])

  Product  Price  Quantity
0     Pen     10       100

4. Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [219]:
data

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [220]:
loc_data=data.loc[3]
loc_data

Product     Pencil
Price            7
Quantity       150
Name: 3, dtype: object

In [221]:
data.loc[0:2]

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200

In [222]:
data

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [223]:
data.set_index('Product',inplace=True)
data

         Price  Quantity
Product
Pen         10       100
Book        50        60
Eraser       5       200
Pencil       7       150

In [224]:
data.iloc[2:3]

         Price  Quantity
Product
Eraser       5       200

In [225]:
data.iloc[1:3,1:3]

         Quantity
Product
Book           60
Eraser        200

5. Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), drop one row by index

In [226]:
df={
    "Name":['Alice','Bob','Charli','Ajme'],
    'City':['A','B','C','D'], 
    'Marks':[55,80,90,88]
}
df=pd.DataFrame(df)
df

     Name City  Marks
0   Alice    A     55
1     Bob    B     80
2  Charli    C     90
3    Ajme    D     88

In [227]:
drop_data=df.drop(0)
print(drop_data)

     Name City  Marks
1     Bob    B     80
2  Charli    C     90
3    Ajme    D     88

In [228]:
df.drop('City',axis=1,inplace=True)
df

     Name  Marks
0   Alice     55
1     Bob     80
2  Charli     90
3    Ajme     88

6. Create a DataFrame of employees with columns "Name", "Department", and "Salary". Sort it by "Salary" in ascending order and by "Name" in descending order.

In [231]:
employees={
    "Name":['Alice','Bob','Charli','Ajme'],
    'Department':['A','B','C','D'], 
    'Salary':[550000,8900,9000,8800]
}
df=pd.DataFrame(employees)
df

     Name Department  Salary
0   Alice          A  550000
1     Bob          B    8900
2  Charli          C    9000
3    Ajme          D    8800

In [241]:
sort_d=df.sort_values(['Salary','Name'],ascending=(True,False))
sort_d

     Name Department  Salary
3    Ajme          D    8800
1     Bob          B    8900
2  Charli          C    9000
0   Alice          A  550000

7. Create a DataFrame of 8 students with columns "Name" and "Score". Filter and print students with Score > 60 and those with Score < 40.

In [242]:
df={
    "Name":['Alice','Bob','Charli','Ajme','Pro','Rafi','Mehran','Mina'],
    'Score':[55,80,90,88,61,8,9,8]
}
df=pd.DataFrame(df)
df

     Name  Score
0   Alice     55
1     Bob     80
2  Charli     90
3    Ajme     88
4     Pro     61
5    Rafi      8
6  Mehran      9
7    Mina      8

In [251]:
fail=df.loc[(df['Score']<40) ]
pass1=df.loc[(df['Score']<60)]
fail

     Name  Score
5    Rafi      8
6  Mehran      9
7    Mina      8