prothomaakter937@gmail.com

#1. NumPy

In [ ]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")

Sample Data Created and Saved as employees.csv

Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.

In [ ]:
ages=np.array(ages)
salaries=np.array(salaries)
print("ages array:",ages)
print("salaries array:",salaries)
print(ages.dtype)
print(salaries.dtype)
print(ages.ndim)
print(salaries.ndim)
print(ages.shape)
print(salaries.shape)
print(ages.size)
print(salaries.size)

ages array: [56 46 32 25 38 56 36 40 28 28]
salaries array: [77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
int64
1
1
(10,)
(10,)
10
10

Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.

In [ ]:
salaries_min=np.min(salaries)
salaries_max=np.max(salaries)
salaries_mean=np.mean(salaries)
print("salaries_min:",salaries_min)
print("salaries_max:",salaries_max)
print("salaries_mean:",salaries_mean)

salaries_min: 30769
salaries_max: 89735
salaries_mean: 57446.9

Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [ ]:

# older_than_30=np.where(ages>30)
older_than_30=[ages>30]
print(older_than_30)
print(np.sum(older_than_30))

[array([ True,  True,  True, False,  True,  True,  True,  True, False,
       False])]
7

Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

In [ ]:
my = np.genfromtxt("employees.csv", delimiter=",", dtype=str, skip_header=1)
print(my)

[['1' '56' '77191' 'HR']
 ['2' '46' '74131' 'IT']
 ['3' '32' '46023' 'Finance']
 ['4' '25' '71090' 'IT']
 ['5' '38' '31685' 'HR']
 ['6' '56' '30769' 'Sales']
 ['7' '36' '89735' 'Finance']
 ['8' '40' '86101' 'IT']
 ['9' '28' '32433' 'Sales']
 ['10' '28' '35311' 'HR']]

In [ ]:
ages = np.array(ages)
ages_new = ages + 5
print(ages_new)
print(type(ages))

[61 51 37 30 43 61 41 45 33 33]
<class 'numpy.ndarray'>

Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.

In [ ]:
salary=np.array(salaries)
salary_expense=np.sum(salary)
salary_difference = np.max(salary) - np.min(salary)
print("salary_expense:",salary_expense)
print("salary_difference:",salary_difference)

salary_expense: 574469
salary_difference: 58966

#2. Pandas

Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().

In [ ]:
import pandas as pd
df=pd.read_csv("employees.csv")
df=pd.DataFrame(df)
df.head(5)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   age     10 non-null     int64
 2   salary  10 non-null     int64
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

Q7. Display only the id, age, and salary columns. Then show the last 3 rows using tail().

In [ ]:
columns1=df[["id","age","salary"]]
columns1.tail(3)

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

Q8. Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.

In [ ]:
it_employees=df.loc[df["dept"]=="IT"]
total_it_employees = it_employees['dept'].count()
print(it_employees)
print(F"Total it employees: {total_it_employees}")

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
Total it employees: 3

Q9. Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.

In [ ]:
salary_dec=df.sort_values('salary',ascending=False)
top_3_highest_paid_employees = salary_dec[['id', 'dept', 'age', 'salary']].head(3)
print(top_3_highest_paid_employees)

   id     dept  age  salary
6   7  Finance   36   89735
7   8       IT   40   86101
0   1       HR   56   77191

Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.

In [ ]:
df.loc[df['salary'] > 80000, 'salary'] = 80000
new_average_salary = df['salary'].mean()
print("New Average Salary of all employees:", new_average_salary)

New Average Salary of all employees: 55863.3